### ISSUE TITLE
is it using the IMU?

### ISSUE THREAD

**Issue by freaad** [ubuntuslave/vo_single_camera_sos#1]
Hello. I have question about this code. is it using the IMU data? Why is it use the ROS?
If it is unnecessary about imu, it also can run in the window right?
Also how can I make the omnicamera for myself.
is there any paper about this? The idea looks fancy I am wondering how can I make it.
Thank you.

**Comment by ubuntuslave** [comment]
No, no use of IMU at all. Pure visual odometry.
